[variables]
main_domain = "${domain}"

[config]
[[config.domains]]
serviceName = "storyden"
port = 8000
host = "${main_domain}"

[config.env]
STORYDEN_FQDN = "http://${main_domain}"

[[config.mounts]]
