version: "3.8"

services:
  borgitory:
    image: mlapaglia/borgitory:latest
    restart: unless-stopped
    expose:
      - 8000
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - borgitory-data:/app/data
      - borgitory-sources:/mnt/sources:ro
      - borgitory-repos:/mnt/repos:ro

volumes:
  borgitory-data: {}
  borgitory-sources: {}
  borgitory-repos: {}
