[variables]
main_domain = "${domain}"

[config]
[[config.domains]]
serviceName = "borgitory"
port = 8000
host = "${main_domain}"

[config.env]

[[config.mounts]]
name = "borgitory-data"
mountPath = "/app/data"
description = "Database and encryption key storage"

[[config.mounts]]
name = "borgitory-sources"
mountPath = "/mnt/sources"
description = "Sources to back up (read-only)"

[[config.mounts]]
name = "borgitory-repos"
mountPath = "/mnt/repos"
description = "Borg repositories (read-only)"