[variables]
main_domain = "${domain}"
TZ = "Europe/London"
BASE_URL = "https://${main_domain}"
SMTP_HOST = ""
SMTP_PORT = "587"
SMTP_AUTH_STRATEGY = "TLS"
SMTP_FROM_NAME = "Mealie"
SMTP_FROM_EMAIL = ""
SMTP_USER = ""
SMTP_PASSWORD = ""
API_DOCS = "False"
ALLOW_SIGNUP = "false"

[config]
[[config.domains]]
serviceName = "mealie"
port = 9000
host = "${main_domain}"

[config.env]
BASE_URL = "${BASE_URL}"
TZ = "${TZ}"
DEFAULT_GROUP = "Home"
DEFAULT_HOUSEHOLD = "Family"
API_DOCS = "${API_DOCS}"
SECURITY_MAX_LOGIN_ATTEMPTS = "10"
SECURITY_USER_LOCKOUT_TIME = "24"
DAILY_SCHEDULE_TIME = "01:00"
ALLOW_SIGNUP = "${ALLOW_SIGNUP}"
SMTP_HOST = "${SMTP_HOST}"
SMTP_PORT = "${SMTP_PORT}"
SMTP_AUTH_STRATEGY = "${SMTP_AUTH_STRATEGY}"
SMTP_FROM_NAME = "${SMTP_FROM_NAME}"
SMTP_FROM_EMAIL = "${SMTP_FROM_EMAIL}"
SMTP_USER = "${SMTP_USER}"
SMTP_PASSWORD = "${SMTP_PASSWORD}"