version: "3.8"

services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    restart: unless-stopped
    expose:
      - 8088
    volumes:
      - cookiecloud-data:/data/api/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8088"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  cookiecloud-data: {}
