[variables]
main_domain = "${domain}"
postgres_password = "${password:32}"

[config]

[[config.domains]]
serviceName = "zabbix-web-nginx-pgsql"
port = 8080
host = "${main_domain}"

[config.env]
POSTGRES_DB = "zabbix"
POSTGRES_USER = "zabbix"
POSTGRES_PASSWORD = "${postgres_password}"
PHP_TZ = "UTC"
ZBX_SERVER_NAME = "Dokploy Zabbix Monitoring"