[variables]
main_domain = "${domain}"
username = "${username}"
password = "${password:16}"
secret_key = "${password:32}"
totp_key = "${password:32}"

[config]
[[config.domains]]
serviceName = "flatnotes"
port = 8080
host = "${main_domain}"
path = "/"

[config.env]
PUID = "1000"
PGID = "1000"
FLATNOTES_AUTH_TYPE = "totp"
FLATNOTES_USERNAME = "${username}"
FLATNOTES_PASSWORD = "${password}"
FLATNOTES_SECRET_KEY = "${secret_key}"
FLATNOTES_TOTP_KEY = "${totp_key}"
FLATNOTES_SESSION_EXPIRY_DAYS = "30"
FLATNOTES_PATH_PREFIX = ""

[[config.mounts]]
name = "flatnotes-data"
mountPath = "/data"
