version: "3.8"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    restart: always
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  uptime-kuma-data:
